"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Activity, ArrowDownToLine, ArrowRight, Check, ChevronLeft, ChevronRight, CircleHelp, FileText, GitFork, Layers, LogOut, RefreshCw, Search, ShieldCheck, SlidersHorizontal, X } from "lucide-react";
import EvidenceGraph from "../components/EvidenceGraph";
import Modal from "../components/Modal";
import { api, type Case, type Detail, type Graph, type Manifest, type Queue, type Score } from "../lib/api";
const demoMoney = (v: number) => new Intl.NumberFormat("en-US", {style: "currency", currency: "USD", maximumFractionDigits: 0}).format(v);
const pct = (v: number) => `${(v * 100).toFixed(1)}%`;
const eventTime = (v: number) => `Day ${Math.floor(v / 86400) + 1} · ${String(Math.floor(v / 3600) % 24).padStart(2, "0")}:${String(Math.floor(v / 60) % 60).padStart(2, "0")}`;
export default function Workspace() {
  const generation = useRef(0);
  const [identity, setIdentity] = useState<{subject: string; organization: string; organization_name: string; roles: string[]} | null>(null);
  const [token, setToken] = useState(""), [draftToken, setDraftToken] = useState("");
  const [tab, setTab] = useState("queue"), [queue, setQueue] = useState<Queue | null>(null), [manifest, setManifest] = useState<Manifest | null>(null);
  const money = (v: number) => manifest?.dataset === "synthetic-demo" ? demoMoney(v) : new Intl.NumberFormat("en-US", {maximumFractionDigits: 2}).format(v);
  const [active, setActive] = useState(""), [detail, setDetail] = useState<Detail | null>(null), [graph, setGraph] = useState<Graph | null>(null);
  const [error, setError] = useState(""), [loading, setLoading] = useState(false), [detailLoading, setDetailLoading] = useState(false);
  const [minScore, setMinScore] = useState("0"), [minAmount, setMinAmount] = useState(""), [entity, setEntity] = useState(""), [after, setAfter] = useState(""), [before, setBefore] = useState("");
  const [offset, setOffset] = useState(0), [search, setSearch] = useState(""), [note, setNote] = useState(""), [status, setStatus] = useState("investigating"), [saving, setSaving] = useState(false), [saved, setSaved] = useState(false);
  const [cases, setCases] = useState<Case[]>([]), [audit, setAudit] = useState<{action: string; subject: string; time: string}[]>([]);
  const [entityInfo, setEntityInfo] = useState<{id: string; max_associated_risk: number; alerts: Score[]; total: number; offset: number; limit: number; notice: string} | null>(null);
  useEffect(() => {setToken(sessionStorage.getItem("fraudgraph-token") || "");}, []);
  const load = useCallback(async (signal?: AbortSignal) => {
    const epoch = generation.current;
    if (!token) return;
    setLoading(true); setError("");
    const params = new URLSearchParams({min_score: minScore, min_amount: minAmount || "0", limit: "30", offset: String(offset)});
    if (entity) params.set("entity_type", entity);
    if (after) params.set("after", after);
    if (before) params.set("before", before);
    try { const [q, m, who] = await Promise.all([api<Queue>(`alerts?${params}`, token, undefined, signal), api<Manifest>("model", token, undefined, signal), api<NonNullable<typeof identity>>("session", token, undefined, signal)]); if (signal?.aborted || epoch !== generation.current) return; setQueue(q); setManifest(m); setIdentity(who); setActive(prev => q.items.some(a => a.id === prev) ? prev : q.items[0]?.id || ""); }
    catch (e) { if (!signal?.aborted && epoch === generation.current) setError((e as Error).message); } finally { if (!signal?.aborted && epoch === generation.current) setLoading(false); }
  }, [token, minScore, minAmount, entity, after, before, offset]);
  useEffect(() => {const controller = new AbortController(); const timer = setTimeout(() => load(controller.signal), 200); return () => {clearTimeout(timer); controller.abort();};}, [load]);
  useEffect(() => {
    if (!active || !token) {setDetail(null); setGraph(null); return;}
    const controller = new AbortController(); setDetailLoading(true); setDetail(null); setGraph(null); setSaved(false); setNote("");
    Promise.all([api<Detail>(`alerts/${active}`, token, undefined, controller.signal), api<Graph>(`alerts/${active}/graph`, token, undefined, controller.signal)])
      .then(([d,g]) => {if (controller.signal.aborted) return; setDetail(d); setGraph(g); setStatus(d.case?.status || "investigating");})
      .catch(e => {if (!controller.signal.aborted) setError(e.message);}).finally(() => {if (!controller.signal.aborted) setDetailLoading(false);});
    return () => controller.abort();
  }, [active, token]);
  useEffect(() => { if (!token) return; const controller = new AbortController();
    if (tab === "cases") api<{items: Case[]}>("cases", token, undefined, controller.signal).then(d => {if (!controller.signal.aborted) setCases(d.items);}).catch(e => {if (!controller.signal.aborted) setError(e.message);});
    if (tab === "audit") api<{items: typeof audit}>("audit", token, undefined, controller.signal).then(d => {if (!controller.signal.aborted) setAudit(d.items);}).catch(e => {if (!controller.signal.aborted) setError(e.message);});
    return () => controller.abort();
  }, [tab, token]);
  function signOut() {generation.current++; sessionStorage.removeItem("fraudgraph-token"); setToken(""); setDraftToken(""); setQueue(null); setManifest(null); setIdentity(null); setActive(""); setDetail(null); setGraph(null); setCases([]); setAudit([]); setEntityInfo(null); setNote(""); setError(""); setOffset(0); setTab("queue");}
  async function save() {const epoch = generation.current;if (!detail || !note.trim()) return; setSaving(true); setError(""); try {const c = await api<Case>(`alerts/${detail.id}/case`, token, {status, note: note.trim()}); if (epoch !== generation.current) return; setDetail({...detail, case: c}); setNote(""); setSaved(true); await load();} catch (e) {setError((e as Error).message);} finally {setSaving(false);}}
  async function exportCase(id: string) {const epoch = generation.current; try {const data = await api(`cases/${id}/export`, token); if (epoch !== generation.current) return; const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], {type: "application/json"})); const a = document.createElement("a"); a.href = url; a.download = `fraudgraph-case-${id}.json`; a.click(); URL.revokeObjectURL(url);} catch (e) {setError((e as Error).message);}}
  async function showEntity(id: string, offset = 0) {const epoch = generation.current; try {const data = await api<NonNullable<typeof entityInfo>>(`entities/${encodeURIComponent(id)}?offset=${offset}`, token); if (epoch === generation.current) setEntityInfo(data);} catch (e) {setError((e as Error).message);}}
  if (!token) return <main className="login"><div className="login-card"><div className="brand"><GitFork size={30}/><b>fraudgraph<span> /</span></b></div><span className="eyebrow">THE INVESTIGATION WORKSPACE</span><h1>Follow the connections.</h1><p>Explore temporal risk signals, inspect shared infrastructure, and document your judgment.</p><form onSubmit={e => {e.preventDefault(); generation.current++; sessionStorage.setItem("fraudgraph-token", draftToken); setToken(draftToken);}}><label htmlFor="token">Analyst access token</label><input id="token" type="password" value={draftToken} onChange={e => setDraftToken(e.target.value)} required autoComplete="off"/><button className="primary">Open workspace <ArrowRight size={17}/></button></form><small>Local demo token: <code>local-demo-token-change-me</code><br/>The default demo uses synthetic data. For configured deployments, use your assigned token.</small></div></main>;
  const visible = queue?.items.filter(r => r.id.toLowerCase().includes(search.toLowerCase())) || [];
  return <div className="shell"><aside className="sidebar"><div className="brand"><GitFork size={25}/><b>fraudgraph<span> /</span></b></div><div className="workspace-label"><span className="workspace-icon">F</span><div>{identity?.organization_name || "Risk operations"}<small>{identity?.subject || "Investigation workspace"}</small></div><span className="tiny-dot"/></div><span className="nav-label">WORKSPACE</span><nav>{[["queue", "Alert queue", Activity], ["cases", "My cases", FileText], ["models", "Model registry", Layers], ["audit", "Audit trail", ShieldCheck]].map(([key, label, Icon]) => <button key={String(key)} className={tab === key ? "nav-item active" : "nav-item"} onClick={() => setTab(String(key))}><Icon size={18}/>{String(label)}{key === "queue" && <span>{queue?.total ?? "—"}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="integrity"><ShieldCheck size={19}/><strong>Evidence before action</strong><p>Shared identifiers are a starting point for investigation.</p></div><button className="nav-item" onClick={() => setTab("help")}><CircleHelp size={18}/>Workspace guide</button><button className="profile" onClick={signOut}><span className="avatar">AN</span><div>Analyst<small>Sign out</small></div><LogOut size={16}/></button></div></aside>
    <main className="main"><header className="topbar"><span>Workspace <ChevronRight size={13}/> <b>{({queue:"Alert queue",cases:"My cases",models:"Model registry",audit:"Audit trail",help:"Workspace guide"} as Record<string,string>)[tab]}</b></span><div><span className="live-dot"/>{manifest?.dataset === "synthetic-demo" ? "Synthetic demo" : "Offline research"}<span className="top-divider"/>Temporal evidence</div></header>
      <div className="content"><div className="page-heading"><div><span className="eyebrow">RISK INTELLIGENCE / {tab === "queue" ? "INVESTIGATE" : tab.toUpperCase()}</span><h1>{({queue:"Every connection tells a story.",cases:"Your investigation record.",models:"Models, with their receipts.",audit:"A traceable decision trail.",help:"From signal to judgment."} as Record<string,string>)[tab]}</h1><p>{tab === "queue" ? "Prioritize the signals. Follow the evidence. Make the call." : "A transparent view of the work behind each decision."}</p></div><button className="secondary" onClick={() => load()} disabled={loading}><RefreshCw size={15} className={loading ? "spin" : ""}/>Refresh</button></div>
      {error && <div className="error" role="alert">{error}<button onClick={() => setError("")} aria-label="Dismiss error"><X size={16}/></button></div>}
      {tab === "queue" && <><section className="stats"><div><span>Transactions in view <Activity size={16}/></span><strong>{queue?.total.toLocaleString() ?? "—"}</strong><small>Ranked by calibrated risk</small></div><div><span>High-risk signals <span className="risk-dot"/></span><strong>{queue?.summary.high_risk ?? "—"}</strong><small>Estimated probability ≥ 50%</small></div><div><span>Flagged transaction value <ArrowRight size={16}/></span><strong>{queue ? money(queue.summary.flagged_value) : "—"}</strong><small>Associated value, not confirmed loss</small></div><div><span>Awaiting your review <FileText size={16}/></span><strong>{queue?.summary.open ?? "—"}</strong><small>Human judgment required</small></div></section>
      <div className="investigation"><section className="queue-panel"><div className="section-title"><h2>Investigation queue <span>{queue?.total ?? 0}</span></h2><SlidersHorizontal size={17}/></div><div className="search"><Search size={16}/><input aria-label="Search current page" placeholder="Find transaction on this page…" value={search} onChange={e => setSearch(e.target.value)}/></div><div className="filters"><label>Risk<select value={minScore} onChange={e => {setMinScore(e.target.value); setOffset(0);}}><option value="0">All scores</option><option value="0.5">High · 50%+</option><option value="0.8">Critical · 80%+</option></select></label><label>Entity<select value={entity} onChange={e => {setEntity(e.target.value); setOffset(0);}}><option value="">All entities</option>{["account","card","device","address","merchant"].map(x => <option key={x}>{x}</option>)}</select></label><label>Min. value<input type="number" min="0" placeholder="0" value={minAmount} onChange={e => {setMinAmount(e.target.value); setOffset(0);}}/></label></div><details className="time-filter"><summary>Time window · seconds from dataset origin</summary><div><label>From<input type="number" min="0" value={after} onChange={e => {setAfter(e.target.value); setOffset(0);}}/></label><label>Through<input type="number" min="0" value={before} onChange={e => {setBefore(e.target.value); setOffset(0);}}/></label></div></details>
      <div className="queue-columns"><span>TRANSACTION / AMOUNT</span><span>RISK SCORE ↓</span></div><div className="queue-list" aria-busy={loading}>{!visible.length && <div className="empty">{loading ? "Loading signals…" : "No transactions match these filters."}</div>}{visible.map(row => <button className={`queue-row ${row.id === active ? "selected" : ""}`} key={row.id} onClick={() => setActive(row.id)} aria-pressed={row.id === active}><span className="transaction-icon"><GitFork size={17}/></span><span className="transaction-text"><strong>{row.id}</strong><small>{money(row.amount)} <i/> {eventTime(row.time)}</small><span className={`status ${row.status === "open" ? "" : "reviewed"}`}>{row.status === "open" ? "Needs review" : row.status}</span></span><span className={`score-pill ${row.score >= .5 ? "high" : "low"}`}>{pct(row.score)}</span><ChevronRight size={14}/></button>)}</div><div className="pagination"><small>{queue?.total ? `${offset + 1}–${Math.min(offset + 30, queue.total)} of ${queue.total}` : "0 results"}</small><div><button aria-label="Previous page" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 30))}><ChevronLeft size={17}/></button><button aria-label="Next page" disabled={!queue || offset + 30 >= queue.total} onClick={() => setOffset(offset + 30)}><ChevronRight size={17}/></button></div></div></section>
      <section className="detail-panel" aria-busy={detailLoading}>{detailLoading ? <div className="empty">Loading transaction evidence…</div> : !detail ? <div className="empty">Select a transaction to inspect its evidence.</div> : <><div className="detail-heading"><div><span className="eyebrow">TRANSACTION DETAIL</span><h2>{detail.id}<span className="outline-tag">{detail.case?.status || "Unreviewed"}</span></h2></div><strong>{money(detail.amount)}<small>{eventTime(detail.time)}</small></strong></div><div className="score-comparison"><div><span>Selected model · {detail.model}</span><strong>{pct(detail.score)}<small>calibrated risk</small></strong><div className="score-track"><i style={{width: pct(detail.score)}}/></div></div><div><span>Logistic baseline</span><strong>{pct(detail.baseline_score)}<small>uncalibrated</small></strong><div className="score-track neutral"><i style={{width: pct(detail.baseline_score)}}/></div></div><div><span>Relational GNN</span><strong>{pct(detail.graph_score)}<small>uncalibrated</small></strong><div className="score-track neutral"><i style={{width: pct(detail.graph_score)}}/></div></div></div>
      <div className="evidence-title"><div><h3>Connected evidence</h3><p>Time-valid relationships around this transaction</p></div><span className="outline-tag">{graph?.nodes.length ?? 0} nodes</span></div>{graph && <EvidenceGraph graph={graph} onEntity={showEntity}/>}{graph?.truncated && <p className="warning">Showing the 60 most recent related transactions of {graph.historical_transactions}.</p>}
      <div className="patterns"><span className="eyebrow">WHAT THE HISTORY SHOWS</span>{graph?.patterns.slice(0, 5).map((p,i) => <p key={p}><span>{String(i + 1).padStart(2,"0")}</span>{p}</p>)}<small>Observed associations, not model attribution. Legitimate users may share infrastructure.</small></div>
      <div className="analyst-note"><div className="section-title"><h3>Analyst assessment</h3>{detail.case && <button className="text-button" onClick={() => exportCase(detail.case!.id)}><ArrowDownToLine size={14}/>Export case</button>}</div><label htmlFor="disposition">Disposition</label><select id="disposition" value={status} onChange={e => setStatus(e.target.value)}>{["investigating","escalated","dismissed","confirmed"].map(s => <option key={s}>{s}</option>)}</select><label htmlFor="note">Investigation note</label><textarea id="note" value={note} onChange={e => {setNote(e.target.value); setSaved(false);}} maxLength={4000} placeholder="Record the evidence, context, and your next step…"/><div className="note-actions"><small>{saved ? <><Check size={14}/> Assessment saved</> : "Every assessment creates an audit record."}</small><button className="primary" disabled={saving || !note.trim()} onClick={save}>{saving ? "Saving…" : "Save assessment"}<ArrowRight size={15}/></button></div>{detail.case?.notes.map((n,i) => <div className="saved-note" key={i}><small>{n.actor} · {new Date(n.time).toLocaleString()}</small><p>{n.text}</p></div>)}</div><footer className="detail-footer"><ShieldCheck size={14}/><span>Model {detail.model_version.slice(0,8)} · Cutoff {detail.cutoff}s<br/>{detail.confidence}</span></footer>{manifest && detail.model_version !== manifest.version && <p className="warning">This alert uses an older model version. Review its provenance before acting.</p>}</>}</section></div></>}
      {tab === "cases" && <section className="document-panel"><h2>My cases <span className="outline-tag">{cases.length}</span></h2>{!cases.length && <p className="empty">Save an assessment from the alert queue to begin a case.</p>}{cases.map(c => <article className="case-row" key={c.id}><FileText size={22}/><div><h3>{c.alert_id}</h3><p>{c.notes.at(-1)?.text}</p><small>{c.status} · {new Date(c.updated).toLocaleString()}</small></div><button className="secondary" onClick={() => {setTab("queue"); setActive(c.alert_id);}}>Inspect</button><button className="secondary" onClick={() => exportCase(c.id)}><ArrowDownToLine size={16}/>Export</button></article>)}</section>}
      {tab === "models" && manifest && <section className="document-panel"><span className="eyebrow">ACTIVE OFFLINE MODEL</span><h2>{manifest.selected}</h2><p>Selected using the earlier validation window. Calibration uses its later half. Final holdout results live in the experiment report.</p><dl><dt>Version</dt><dd>{manifest.version}</dd><dt>Dataset</dt><dd>{manifest.dataset}</dd><dt>Graph schema</dt><dd>{manifest.graph_schema}</dd><dt>Seeds</dt><dd>{manifest.seeds.join(", ")}</dd><dt>Alert budget</dt><dd>Top {manifest.policy.top_k} per evaluation window</dd><dt>Dataset checksum</dt><dd>{manifest.dataset_sha256}</dd><dt>Code checksum</dt><dd>{manifest.code_sha256}</dd><dt>Calibration</dt><dd>{manifest.calibration}</dd></dl><h3>Feature definitions</h3><div className="feature-tags">{manifest.features.map(f => <code key={f}>{f}</code>)}</div></section>}
      {tab === "audit" && <section className="document-panel"><h2>Your audit trail</h2>{!audit.length && <p className="empty">Your saved assessments, exports, and batch jobs will appear here.</p>}{audit.map((a,i) => <article className="audit-row" key={i}><ShieldCheck size={18}/><strong>{a.action.replaceAll("_", " ")}</strong><code>{a.subject.slice(0,20)}</code><small>{new Date(a.time).toLocaleString()}</small></article>)}</section>}
      {tab === "help" && <section className="document-panel prose"><h2>Investigate in five steps</h2><ol><li>Filter the queue by score, amount, event time, or available entity types.</li><li>Select a transaction. Compare the serving estimate with the logistic and relational GNN scores.</li><li>Explore shared signatures. The graph includes the focal event and strictly earlier history. Select nodes to highlight their connections; use the accessible entity list for association summaries.</li><li>Record a disposition and a note. A confirmation records your assessment; it does not automatically block an account or retrain a model.</li><li>Export the case with its evidence, cutoff, and model version.</li></ol><h3>Read scores in context</h3><p>Check the model registry for the active dataset and model version. Synthetic demos cannot establish real-world accuracy; public research cohorts also require broader validation. Scores are calibrated estimates, not guarantees. Baseline and GNN comparison scores are uncalibrated. The graph shows relationships, not causal explanations.</p><h3>Time and money</h3><p>Times are relative to the dataset origin. The synthetic fixture uses USD as a display assumption. Public-data amounts are shown in source units without asserting a currency. Missing identifiers are omitted, never merged into a common unknown entity.</p></section>}
      <footer className="page-footer"><span>FRAUDGRAPH <i/> Connected evidence. Considered decisions.</span><span>Research workspace · Human review required</span></footer></div></main>
      {entityInfo && <Modal onClose={() => setEntityInfo(null)}><section className="modal"><button className="modal-close" onClick={() => setEntityInfo(null)} aria-label="Close entity details" autoFocus><X size={20}/></button><span className="eyebrow">ENTITY ASSOCIATIONS</span><h2>{entityInfo.id.split(":")[0]} · {entityInfo.id.slice(-6)}</h2><p>Highest associated alert risk: <b>{pct(entityInfo.max_associated_risk)}</b></p><p>{entityInfo.notice}</p><p>Showing {entityInfo.offset + 1}?{entityInfo.offset + entityInfo.alerts.length} of {entityInfo.total} associated alerts.</p><div><button disabled={entityInfo.offset === 0} onClick={() => showEntity(entityInfo.id, Math.max(0, entityInfo.offset - entityInfo.limit))}>Previous</button><button disabled={entityInfo.offset + entityInfo.limit >= entityInfo.total} onClick={() => showEntity(entityInfo.id, entityInfo.offset + entityInfo.limit)}>Next</button></div><div className="entity-alerts">{entityInfo.alerts.map(a => <button key={a.id} onClick={() => {setActive(a.id); setEntityInfo(null);}}>{a.id}<span>{pct(a.score)}</span></button>)}</div><button className="secondary" onClick={() => setEntityInfo(null)}>Close</button></section></Modal>}
  </div>;
}
